[ADD] add conv1d and support 5d of binary op
Tencent/TNN pull request #1134
Opened 2021-07-12 08:24 UTC by 1627180283

2021-07-12 12:21 UTC, lnmdlong commented on source/tnn/device/opencl/acc/opencl_reduce_layer_acc.cc
> +        }
实现方案需要讨论，第一要考虑的为什么不是用通用的kernel做reduce，非keep dims的情况下做squeeze，第二是axis<3，axis=0的reduce没有实现，但是看起来是满足准入条件的?而且为什么单独axis=3没有实现，如果有特殊原因的话，应该在算子上面判断返回错误码，并添加注释说明

2021-07-12 12:21 UTC, lnmdlong commented on source/tnn/device/opencl/acc/opencl_squeeze_layer_acc.cc
> +REGISTER_OPENCL_ACC(Squeeze, LAYER_UNSQUEEZE)
这个添加的目的是什么，是否验证过正确性

2021-07-12 12:21 UTC, lnmdlong commented on test/unit_test/layer_test/test_reduce_op_layer.cc
> +    if (DEVICE_OPENCL == dev && keep_dims != 1 && axis.size() > 1) {
多维的reduce可以通过添加squeeze算子的方案实现，讨论后确定

2021-07-13 03:47 UTC, darrenyao87 requested changes

2021-08-10 12:10 UTC, closed without merging